name: website
description: Evans Stenakis' website
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/backgrounds/
    - assets/logos/


  fonts:
  - family: Geologica
    fonts:
      - asset: assets/fonts/Geologica-Regular.ttf
        weight: 400
      - asset: assets/fonts/Geologica-Bold.ttf
        weight: 600
      - asset: assets/fonts/Geologica-Black.ttf
        weight: 900
      - asset: assets/fonts/Geologica-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Geologica-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Geologica-Light.ttf
        weight: 300
      - asset: assets/fonts/Geologica-Medium.ttf
        weight: 500
      - asset: assets/fonts/Geologica-SemiBold.ttf
        weight: 700
      - asset: assets/fonts/Geologica-Thin.ttf
        weight: 100

